### PR TITLE
Modernize code for v7/basics: IdentityServerHost, SimpleAPI and MVC client

### PR DESCRIPTION
**Pull request by RolandGuijt**

### CODE REVIEW

**Comment by RolandGuijt** [comment]
#191

**Comment by RolandGuijt** [comment]
@josephdecock Sure. Can you give me a link or show some code snippet that shows how to do that?

**Comment by josephdecock** [comment]
Sure, we just enable this flag in the OIDC handler: https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions.disabletelemetry?view=aspnetcore-8.0#microsoft-aspnetcore-authentication-openidconnect-openidconnectoptions-disabletelemetry.

**Comment by RolandGuijt** [comment]
Added. #183

**Review by brockallen — APPROVED** [review]

**Pull request merged**
