### PR TITLE
Updated grant type from implicit to code flow for AspNetIdentitySample

### PR DESCRIPTION
**Pull request by GFoley83**
Makes sense given the industry shift away from implicit grant.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Why is that better in this particular case?

**Comment by GFoley83** [comment]
You tell me! I would have assumed it would be a better starting example to encourage developers towards code flow, given it's more in keeping with modern standards no?

**Comment by leastprivilege** [comment]
Well - this is a pure OIDC authN flow. I like using implicit flow for that since it does not require a client secret.

For consistency sake, I agree - code flow would be the obvious choice.

**Comment by brockallen** [comment]
So where do we stand on this? Close it seems?

**Comment by GFoley83** [comment]
That's your call. Did you want me to change something? Your last comment sounded to me like you were fine with the PR the way it is?

**Comment by brockallen** [comment]
It was more of a question for @leastprivilege. I think he and are prefer implicit if all the client app needs is OIDC login.

**Comment by leastprivilege** [comment]
For authN only, this is still the recommeded minimal approach.

**Pull request closed without merging**
