### PR TITLE
Update .NET Framework Sample

### PR DESCRIPTION
**Pull request by josephdecock**

### CODE REVIEW

**Comment by leastprivilege** [comment]
Please put those sample(s) here: https://github.com/DuendeSoftware/Samples/tree/main/various/clients

**Comment by josephdecock** [comment]
I put both the MVC and WebForms sample in the various/clients directory. The only thing not there is a new API built with .NET Framework, which I put in the same directory as the existing APIs.

**Comment by josephdecock** [comment]
@leastprivilege should I move the new api as well or keep it with the existing apis?

**Comment by leastprivilege** [comment]
Move the API as well

**Pull request merged**
