### PR TITLE
feat: ✨ Created AngularBffSample

### PR DESCRIPTION
**Pull request by marleypowell**
https://github.com/DuendeSoftware/IdentityServer/discussions/215

image

image

image

### CODE REVIEW

**Comment by marleypowell** [comment]
@brockallen

**Comment by leastprivilege** [comment]
Thank you very much! The problem with externally contributed samples is maintenance. Ultimately we become responsible of keeping the sample up to date.

If you give us the URL to your repo, we can put that on a list of external samples so our uses can find it more easily.

**Comment by marleypowell** [comment]
https://github.com/marleypowell/DuendeSamples/tree/marley/angular-sample/IdentityServer/v6/BFF/AngularBffSample

**Comment by barelabs** [comment]
Your Angular BFF example was super useful to me on an app I'm building, as there were no angular samples anywhere on the web.  I just tried this and it works perfectly....it's from the base template Microsoft provides, with showing how to set up Angular with the BFFhost.  Thank you for showing how to set this up -- hopefully this can go in the repo, as I'm sure this will help others.

**Comment by leastprivilege** [comment]
I can totally see the value in an Angular sample - but unfortunately we cannot accept huge code contributions from 3rd parties anymore.

We will work on adding our own sample ASAP.

Thanks for understanding.

**Pull request closed without merging**
