### PR TITLE
Replace domains with *.example.com ones #209

### LINKED ISSUE #209: Use example.com subdomains instead of "real" domain names
The samples are referring to "real" domain names such as alice.com, bob.com, and email.com. I would propose to change that to, say, alice.example.com, bob.example.com, and email.example.com to make crystal-clear that these really are examples. Just imagine one of those domains (especially the first two) gets cybersquatted.

### PR DESCRIPTION
**Pull request by wenz**
Replaces alice.com, bob.com, and email.com with {alice|bob|email}.example.com.

Fixes #209

### CODE REVIEW

**Comment by wenz** [comment]
`email.com` now replaced with `example.com`.

**Comment by RolandGuijt** [comment]
Thanks!

**Review by RolandGuijt — APPROVED** [review]

**Comment by RolandGuijt** [comment]
We had some troubles that prevent us from merging this. Can you please the branch to the current main? @wenz

**Comment by wenz** [comment]
"This branch has no conflicts with the base branch" -> what should I do?

**Comment by josephdecock** [comment]
There are fixes to the build in main that aren't in your branch, so we need to merge the latest from main into your branch (or rebase your branch onto that).

**Comment by wenz** [comment]
This should do it!

**Comment by josephdecock** [comment]
Thanks a lot!

**Pull request merged**
